name: Unit test and coverage

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.1.0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'adopt-openj9'
        java-version: '17'
        cache: maven
    - name: Run Unit Tests
      run: ./mvnw test
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: target/jacoco-report/jacoco.xml
